version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discard_paths: no
  base_directory: dist

