version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - frontend/dist/**/*
  discard-paths: yes
 

