version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
      - pwd
      - cd ..
artifacts:
  files:
    - frontend/build/**/*
