version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd frontend
      - npm install
      - echo "$PWD"
  build:
    commands:
      - echo "$PWD"
      - npm run build
      - ls frontend/build

